# Tell ArgoCD where to find the ubiquitous-journey project
source: https://github.com/inderspoc/istio-bootstrap.git
team: labs
release: ci-cd

applications:
  - name: istio-setup
    enabled: true
    source_path: "."
    helm_values:
      - ubiquitous-journey/values-tooling.yaml



